### ISSUE TITLE
Selecting temperature units

### ISSUE THREAD

**Issue by birgador** [dovrosenberg/foundry-simple-weather#10]
Hi! 

First of all, thanks a lot for creating this module. I have been using it a bit and it's great! However, I was wondering if there is a way to switch between Celsius and Fahrenheit units. There may be an option already, but I have not been able to see it.

Thanks!

**Comment by dovrosenberg** [comment]
Unless it's broken, each player (and GM) should have a setting (in the main settings dialog) to switch. Let me know if it doesn't work for you....
