### ISSUE TITLE
[Request] Option to choose the weather for the day

### ISSUE THREAD

**Issue by SesuUisu** [dovrosenberg/foundry-simple-weather#12]
There are situations when your player characters need some special treatment like a Snowstorm in summer because there is a ice witch, or a sunny day when the table expects rain. But the players shouldn't see thousands of chat outputs till you get the result you want.

**Comment by dovrosenberg** [comment]
Why not just put it in the chat manually?  Or is the idea you still want it to show in the weather box for players who have it open?

A couple thoughts, depending on usage need...
1. Perhaps a "silence" checkbox that would pause chat messages and maybe make player weather boxes blank until turned off; you could then override manually by just putting in the chat what you want.  Now that I type this out, I suspect the answer is there's value in not having it be clear to the players that you're doing something different than usual.

2. Some sort of picker where you could manually specify "blizzard" or whatever

Note that next up on the "big" feature list is the ability to display weather effects (using core/weatherFX/FXMaster depending on what's installed).  This would be another argument for option (2) being more useful than option (1).

So, assuming option 2, the next question is do we:
a) have a short list of options and then you somehow say "go back to normal" and it goes back to picking randomly based on the calendar (presumably starting the same way it does if you were just to skip to a random day in a new season)?  
b) let you pick from any of the existing options and are you actually moving the weather to that state?  So, the day after the blizzard, it would be cold but moving back toward seasonal, for example.  

Option B feels like it could be interesting, but also not what you necessarily would want (ex. when you kill the ice witch it shouldn't necessarily still be colder than normal).  Option B also would eliminate the need for dealing with even more weather combinations, but also raises questions like should you only be able to pick from the weather types in the current climate/humidity?  Probably not, given the use case you described.

So, I think I've talked myself into 2A, with the need to pick from a completely new (but abbreviated) list of weather choices and then manually specify a temperature, too.

So, I'm imagining a flow where you hit "pause" and that turns off updates to chat and weather boxes.  You then pick what you want and "push" it out as the new weather.  This way, if you change days on the calendar before you pick the new weather, it won't send an extra notice out - you'll have complete control over what goes to the players.  When you turn off "pause" it does nothing until the day changes again or you hit "regenerate".

But then what options should be in the selection list?

**Comment by SesuUisu** [comment]
With option 2a you have described what I had in mind. 
In my world/setting, there are spells for changing the weather completely. The more extreme the difference the better you have to be with your spell. If you are a master of the spell you can create a blizzard within a sand desert, or create a heat wave in the snow region in winter. 
I assume that other settings and campaign have also spells or godly powers that can have a similar effect. So all possible weather should be possible in all seasons. 

Maybe having the "normal" (seasonal) weather available easier and the other only after checking a box?

**Comment by dovrosenberg** [comment]
Implemented in v1.5.0 (will be released to foundry later today)
