### ISSUE TITLE
Weather Control dialogue box disappears upon Foundry finishing loading.[BUG]

### ISSUE THREAD

**Issue by fishrobe** [dovrosenberg/foundry-simple-weather#15]
After experimenting a few times and Simple Weather working great, the dialogue box to generate weather disappeared. I tried uninstalling/reinstalling Simple Weather, toggling Simple Calander, and reloading Foundry (Forge). 

**Describe the bug**
The Grey dialogue box appears as a big rectangle in the upper left corner while Foundry is loading everything, but then it vanishes. It shows no info except for 27C, and then it disappears. (this is on the most recent Foundry V.11/PF2e)

**To Reproduce**
1. Don't know how it started. I was working and then just suddenly disappared.
2. Reload Foundry in Browser
3. See Simple Weather control panel as Foundry is loading assets.
4. Simple Weather disappears when everything else loads

**Expected behavior**
I was hoping I'm just stupid and there is a button somewhere to turn it back on (like Simple Calander has the toggle for it under Journal Entries/Map Notes)

**Screenshots**
Can provide if needed, but since there's nothing there, I didn't bother

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser Vivaldi 
 - Version 6.2.3105.58

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by fishrobe** [comment]
![simple weather gone](https://github.com/dovrosenberg/foundry-simple-weather/assets/50474856/b81cfd96-cc67-4fbb-aa93-09b6f15aa3bb)
Here is a screenshot of where it appears in Foundry, between when Forge is showing "Downloading World Data" and when everything is loading into Foundry. Then it goes away.

**Comment by fishrobe** [comment]
Ok so oddly after doing Find the Culprit! it showed Talis Dice as the thing that was blocking Simple Weather from showing. However, when I reactivated all modules to turn off Talis Dice, the Weather Control Panel returned, and for now it there without me needing to disable anything. It seems like cycling through Find the Culprit somehow fixed it without needing to turn anything off. Probably even harder to replicate now, but I will leave this here in case someone wants to figure it out, or if it comes up for anyone else.

**Comment by dovrosenberg** [comment]
So... there is bug/odd behavior here.  The box showing during loading is something I want to get rid of.  What I suspect may be happening is that you see the "bad" loading box and then when it fully loads, the dialog moves and is actually just hidden behind something on the screen.  It does save the location - so it should appear (after loading is complete) where you left it last time.  But the box that shows during loading is not in the same place. :(

Could that explain what you saw?

**Comment by fishrobe** [comment]
That's what I thought, but moving / closing any other open boxes on the
screen didn't reveal anything (I had the panel in the lower right, but I
checked everywhere else too). Anyway, weirdly it's working for now. Have no
idea how cycling modules with Find the Culprit could have fixed it, but if
it happens again I'll check back.
