### ISSUE TITLE
Season bound to Simple Calendar

### ISSUE THREAD

**Issue by SesuUisu** [dovrosenberg/foundry-simple-weather#3]
I want to open the discussion on seasons.
a) Simple Calendar has Icons for different seasons: You could bind Simple Weather seasons to that icons. That way the GM has only to set it up in SC how they want it. No need to change anything in SW. If you switch your calendar, your seasons switch accordingly if it is setup there.
b) The issue you are describing is already an issue in SC. So if you consider that, you have to change it in SC and SW. If SW is just taking the info from SC, it is one module less to maintain as a GM and you just setup a copy of the calendar with opposite seasons.
c) Maybe adding the option of switching between northern and southern hemisphere?

**Comment by dovrosenberg** [comment]
OK - So a proposed approach here for any comments:

1. Look up current season in Simple Calendar (if present).  If it has an icon in the set (spring, summer, winter, fall), then set the season selection drop-down in the GM's weather box accordingly.  If it does not have an icon, the season drop-down will not be updated.
2. If using the date/time box, the season name will show there with the appropriate icon (but only if it's one of those 4, to avoid confusion)
3. GM can manually override the season drop down (for ex. to account for opposite hemisphere)
4. If season drop-down is overridden, it will not change until the SEASON changes.  So, for example, when the weather updates the next day it will still use the manually-set season value, not the one from the calendar.

**Comment by SesuUisu** [comment]
Sounds good to me.

**Comment by dovrosenberg** [comment]
Released in v1.3.0
