### ISSUE TITLE
[BUG] When window closed, no option to re-open it (keybinding doesn't work if closed with "X")

### ISSUE THREAD

**Issue by SesuUisu** [dovrosenberg/foundry-simple-weather#36]
After closing SW window via [x], it is closed forever. A button in the note pin menu (left side) would be great (or any other option).

**Comment by dovrosenberg** [comment]
I was thinking it would just add clutter over there... The current option is to bind a keystroke to (display/hide window) and use that to bring it back.  Though I now see there's a bug that keeps that from working.  So, I'm editing the title here and will fix that shortly.  Will also create a new feature request for adding a button to see if folks prefer that.

**Comment by dovrosenberg** [comment]
Fixed in v1.6.3
