### ISSUE TITLE
Missing Localization for Weather description

### ISSUE THREAD

**Issue by SesuUisu** [dovrosenberg/foundry-simple-weather#4]
Weather descriptions can't be localized as they are hardcoded in /src/weather/climateData.ts

**Comment by dovrosenberg** [comment]
Yeah... I saw that one coming. :)   Was just trying to avoid the tedious task of moving them all over.  If it's something you need, though, I'm happy to do it.  Also happy to add a new language file to the package if you want to create one.

**Comment by dovrosenberg** [comment]
@SesuUisu - I have refactored the weather descriptions in the v1.2.0 branch.  I ran the English ones through chatGPT to get a start at the German file (and incorporated what you provided for the v1.1.0 localizations).  Could you take a look at that branch and clean up any poor translations?  Then, if any changes needed, create a PR on the v1.2.0 branch?  Much appreciated.

**Comment by SesuUisu** [comment]
Thanks! I have corrected ChatGPT in #2 
Some feedback for ChatGPT: As your localization is having duplicates (I assume for easier handling in code instead for easier translation), it will translate it everytime instead of copying it. So you will have different translations for the same word. In addition to that, it uses non-common words. I do not recommend ChatGPT for translation for other projects in its current state. 

Just use my GitHub name for the credits ;)

**Comment by dovrosenberg** [comment]
Yeah - figured.  But it let me run huge chunks through at a time and gave it back in a format I could just copy and paste, and I figured it would be easier for you to have something to start with vs. having to do them all by hand. :) Appreciate the help!

**Comment by dovrosenberg** [comment]
Added in v1.2.0
