### ISSUE TITLE
[BUG] Unable to reopen the simple weather gadget after closing it

### ISSUE THREAD

**Issue by Dyrnwyrm** [dovrosenberg/foundry-simple-weather#41]
**Describe the bug**
As the title says by mistake i closed the SW menu on the canvas and now i cant open it on my world, i tried to use different keybinds but nothing worked, no console errors or something like that.

**To Reproduce**
1. Close the SW menu on the canvas
2. Try to open it using a keybind
3. Nothing Happens
4. Disabling and enabling the module does not fix the issue

Foundry Version: 11.315
DnD5e version: 2.3.1
Simple Weather Module Version: 1.7.0

![image](https://github.com/dovrosenberg/foundry-simple-weather/assets/129613553/ede843f7-d015-4775-93a2-d7cd8761248c)

**Comment by dovrosenberg** [comment]
Running in a browser or foundry desktop?  What keybind(s) did you try?  Did you try refreshing (F5)?

**Comment by Dyrnwyrm** [comment]
Logging as GM foundry desktop i tried refreshing and nothing

i tried using ctrl+1 or the - key and nothing

**Comment by dovrosenberg** [comment]
Could you try this:

- Open Foundry
- Hit F12 to open the console
- At the ">" symbol in the window that opens, type
  - `game.settings.get('simple-weather','displayOptions')`
  - Then type `game.settings.get('simple-weather','dialogDisplay')`
  - Then type `game.settings.get('simple-weather','windowLocation')`
- Then send a screenshot of the results

**Comment by Dyrnwyrm** [comment]
![image](https://github.com/dovrosenberg/foundry-simple-weather/assets/129613553/97967106-671a-4133-ae7f-5512fd1b40a3)


Here

**Comment by dovrosenberg** [comment]
Oops... that should have been windowPosition not windowLocation

**Comment by dovrosenberg** [comment]
And can you send me a list of active modules? I can't reproduce this, but you're at least the 2nd person with a similar issue.  I'm wondering if it's some inter-module issue.

**Comment by Dyrnwyrm** [comment]
![image](https://github.com/dovrosenberg/foundry-simple-weather/assets/129613553/f8b96788-464c-4fec-a928-88c69401c8bf)


Got this error today after the update

![image](https://github.com/dovrosenberg/foundry-simple-weather/assets/129613553/d8fe6473-ea2b-43fa-acfe-d860c6b535a1)

And here is the modules i use, sorry for taking so long to answer

### Active Modules
Action Pack v11.2 [Bugs URL](https://github.com/teroparvinen/foundry-action-pack/issues)
Active-Auras v0.8.3 [Bugs URL](https://github.com/kandashi/Active-Auras/issues)
Active Token Effects v0.7.0 [Bugs URL](https://github.com/kandashi/Active-Token-Lighting/issues)
Anonymous v1.4.4 [Bugs URL](https://github.com/reonZ/anonymous/issues)
Arms Reach v2.3.4 [Bugs URL](https://github.com/p4535992/foundryvtt-arms-reach/issues)
Build-a-Bonus v11.4.2
Carousel Combat Tracker v2.5.4
Chat Portrait v0.9.4 [Bugs URL](https://github.com/p4535992/foundryvtt-chat-portrait/issues)
Combat Booster: Turn Marker, Recent Actions and more v3.6.1
DDB-Importer: A D&D Beyond Integrator v3.5.9
DFreds Convenient Effects v6.0.0 [Bugs URL](https://github.com/DFreds/dfreds-convenient-effects/issues)
DFreds Droppables v3.0.1 [Bugs URL](https://github.com/DFreds/dfreds-droppables/issues)
DFreds Effects Panel v3.1.0 [Bugs URL](https://github.com/DFreds/dfreds-effects-panel/issues)
Dice So Nice! v4.6.8 [Bugs URL](https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues)
DND5E Scriplets - 5E QOL bits and pieces v0.20
Dynamic effects using Active Effects (DAE) v11.0.23 [Bugs URL](https://gitlab.com/tposney/dae/-/issues)
Midi QOL v11.1.11 [Bugs URL](https://gitlab.com/tposney/midi-qol/-/issues)
Chris's Premades v0.8.25
Effect Macro v11.0.3
Foundry Redirect: Better invitation links v2.0.4
FXMaster v4.0.2 [Bugs URL](https://github.com/ghost-fvtt/fxmaster/issues)
Grid Scaler v1.4.4
Health Estimate v31.7.9 [Bugs URL](https://github.com/mclemente/healthEstimate/issues)
Hourglass v1.7.0
Illandril's Inventory Sorter (5e) v2.3.0 [Bugs URL](https://github.com/illandril/FoundryVTT-inventory-sorter/issues)
Item Collection\Item Container for Dnd5e v11.0.3
Item Piles v2.8.1 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues)
Items with Spells DnD5e v11.0.5 [Bugs URL](https://github.com/krbz999/foundryvtt-items-with-spells-5e/issues)
JB2A - Patreon Complete Collection v0.6.2
Kris's Compendium of Trade Goods v0.13
lib - Color Settings v2.9.1
🏷️ Item Tags (Library) v1.1.0 [Bugs URL](https://github.com/ZotyDev/FoundryVTT-ItemTags/issues)
libWrapper v1.12.13.0 [Bugs URL](https://github.com/ruipin/fvtt-lib-wrapper/issues)
socketlib v1.0.13 [Bugs URL](https://github.com/manuelVo/foundryvtt-socketlib/issues)
Limits v1.0.2 [Bugs URL](https://github.com/dev7355608/limits/issues)
Universal Battlemap Importer v3.0.0
Mass Edit v1.44.8
Material Components v11.1.3 [Bugs URL](https://github.com/M0nk3yy/MC5e/issues)
Module Management+ v2.2.3 [Bugs URL](https://github.com/mouse0270/module-credits/issues)
Monk's Bloodsplats v11.07 [Bugs URL](https://github.com/ironmonk88/monks-bloodsplats/issues)
Monk's Combat Details v11.08 [Bugs URL](https://github.com/ironmonk88/monks-combat-details/issues)
Monk's Combat Marker v11.03 [Bugs URL](https://github.com/ironmonk88/monks-combat-marker/issues)
Monk's Enhanced Journal v11.07 [Bugs URL](https://github.com/ironmonk88/monks-enhanced-journal/issues)
Monk's Player Settings v11.04 [Bugs URL](https://github.com/ironmonk88/monks-player-settings/issues)
Monk's TokenBar v11.05 [Bugs URL](https://github.com/ironmonk88/monks-tokenbar/issues)
Monk's Wall Enhancement v11.02 [Bugs URL](https://github.com/ironmonk88/monks-wall-enhancement/issues)
Perceptive v2.8.3
Polyglot v2.3.14
Rarity Colors v0.3.7 [Bugs URL](https://github.com/p4535992/foundryvtt-rarity-colors/issues)
Rest Recovery for 5E v1.4.17
Reverse Initiative Order v1.2.1 [Bugs URL](https://github.com/sun-dragon-cult/fvtt-module-reverseinitiativeorder/issues)
Revised Weapons & Equipment v11.0.0
Rideable v2.15.10 [Bugs URL](https://github.com/Saibot393/Rideable/issues)
routinglib v1.1.0 [Bugs URL](https://github.com/manuelVo/foundryvtt-routinglib/issues)
Sequencer v3.1.4 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Sequencer/issues)
Automated Animations v4.2.68
D&D5e Animations v1.6.0
✨ Automated Objects, Interactions and Effects 🔥 v1.1.4.1 [Bugs URL](https://github.com/ZotyDev/objects-interactions-fx/issues)
Show Token Art v1.0.3
Shuggaloaf's Simple NPC Generator vv4.0.11
Simple Calendar v2.4.3 [Bugs URL](https://github.com/vigoren/foundryvtt-simple-calendar/issues)
Simple Weather v1.7.1 [Bugs URL](https://github.com/dovrosenberg/foundry-simple-weather/issues)
SmallTime v1.19.1 [Bugs URL](https://github.com/unsoluble/smalltime/issues)
Smart Target v1.0.1 [Bugs URL](https://github.com/theripper93/Smart-Target/issues)
Stairways (Teleporter) v0.10.2 [Bugs URL](https://gitlab.com/SWW13/foundryvtt-stairways/issues)
Tagger v1.4.5 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Tagger/issues)
Template Macro v11.0.1
Tidy5e Sheet v0.9.18 [Bugs URL](https://github.com/sdenec/tidy5e-sheet/issues)
Times Up v11.0.3 [Bugs URL](https://gitlab.com/tposney/times-up/-/issues)
Token Attacher vv4.5.13
Token Auras v2.7
Token Magic FX v0.6.5.0
Token Mold v2.20.3 [Bugs URL](https://github.com/Moerill/token-mold/issues)
Token Variant Art v4.59.0 [Bugs URL](https://github.com/Aedif/TokenVariants/issues)
Token Warp v11.0.1.1 [Bugs URL](https://github.com/thatlonelybugbear/token-warp/issues)
Variant Encumbrance+Midi vv0.13.5 [Bugs URL](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/issues)
Vision 5e v1.10.4 [Bugs URL](https://github.com/dev7355608/vision-5e/issues)
Walled Templates v0.6.10
Wall Height v5.0.3
Warp Gate v1.19.0
Arbron’s Summoning v1.1.4 [Bugs URL](https://github.com/arbron/fvtt-summoner/issues)

**Comment by dovrosenberg** [comment]
In the console, can you try: 

`game.settings.set('simple-weather', 'windowPosition', {left:0, bottom:0})` and then wait a second or two and then refresh (F5).

**Comment by Dyrnwyrm** [comment]
No box after doing that console command, by the way i got this error now after the update, maybe its related to the issue?

![image](https://github.com/dovrosenberg/foundry-simple-weather/assets/129613553/0ac43c13-5393-4e9e-a4b8-e1214c6f4572)

**Comment by dovrosenberg** [comment]
Can you show me your configuration settings box like the picture I posted at the top?  Also, above the getData debug stuff you posted, did it show a value for `currentlyHidden`?

**Comment by dovrosenberg** [comment]
I think upgrading to 1.7.2 will fix that console error, so we can see if it's related.

**Comment by Dyrnwyrm** [comment]
Upgrading to 1.7.2 fixes the issue of the invisible window and the console error

**Comment by SesuUisu** [comment]
I had the same issue, but after upgrading to 1.7.2, I had to start once without anyother module than Simple Weather. Otherwise it still didn't shown (just for record if someone else has the same problem).

**Comment by dovrosenberg** [comment]
is the console error still there?

**Comment by Dyrnwyrm** [comment]
Nope, both issues are fixed thanks for the quick fix

**Comment by dovrosenberg** [comment]
Cool... let me know if it comes back.  Can you clarify what fixed it?  You loaded the world with no other modules?  Then it showed up and you added all the other modules back?

**Comment by Dyrnwyrm** [comment]
Just updated the module and opened the world after that, no extra steps

**Comment by SesuUisu** [comment]
> Cool... let me know if it comes back.  Can you clarify what fixed it?  You loaded the world with no other modules?  Then it showed up and you added all the other modules back?

I had to load the World without any extea module. After that i had the SW back and could load the other modules without issue.
