### ISSUE TITLE
[BUG] Sync with calendar setting not saving between sessions

### ISSUE THREAD

**Issue by cwlithgow** [dovrosenberg/foundry-simple-weather#44]
**Describe the bug**
The "Sync with Simple Calendar" selection doesn't save between sessions.

**To Reproduce**
1. Choose "Sync with Simple Calendar" option. Assume it is Summer in Simple Calendar
2. F5 your browser or log-out of Foundry Session.
3. Log into a new foundry session - same world.
4. Season symbols are still the same but the dialog box now reads "Summer" rather than Sync with Calendar
5. Advance Simple Calendar to a new season and notice that the season does not change in Simple Weather as it should

**Screenshots**
Before Refresh or log out-in.
![image](https://github.com/dovrosenberg/foundry-simple-weather/assets/85030999/ee90a014-a7c4-4ea5-bb9c-60568b8c249b)

After Refresh or log out-in
![image](https://github.com/dovrosenberg/foundry-simple-weather/assets/85030999/ec1e7a53-211b-4763-8df8-0719a7548110)

Foundry V11 Build 315
The One Ring 2nd edition 3.3.7
I have reproduced the issue in a no-other-module environment, but have not tried with any other game systems.

I appreciate your time and efforts!

**Comment by dovrosenberg** [comment]
Fixed in 1.8.1

Thanks for reporting it!
