### ISSUE TITLE
[REQUEST] Better integration with Simple Calendar UI

### ISSUE THREAD

**Issue by marcstraube** [dovrosenberg/foundry-simple-weather#46]
Together with Simple Calendar (and eventually Small Time), the screen gets extremely cluttered, especially using Foundry on a small Notebook.

It would be a nice feature to just have a weather icon next to Simple Weather's season and moon-phase icons, that would open the weather configuration. This way you won't need to have two calender apps opened.

Example Screenshot:
![simple-calender-and-weather](https://github.com/dovrosenberg/foundry-simple-weather/assets/52066916/0270391d-d3f0-4c68-816a-339f448c731a)

**Comment by skarr71** [comment]
This!! Please add this function.

**Comment by dovrosenberg** [comment]
I'm going to work on this.  

In the meantime I also released 1.8.2 which includes a working button inside the journal scene controls to show the dialog.  With that, you can disable the calendar side of the box (see readme) and then hide the box with the "x" and redisplay it with this control button.  Alternately, you can create a keybinding to toggle the display on-off.  With that approach, you can get most of the benefit of having the UI you show above, except that the dialog won't move around with the simple calendar dialog.

**Comment by dovrosenberg** [comment]
Released in 1.9.0.  Leaving this open until a 1.9.1 release that includes updated documentation showing the button, but it's fully functional now.

**Comment by dovrosenberg** [comment]
Complete with 1.9.1
