### ISSUE TITLE
[BUG/FEATURE REQUEST] FXMaster can take a really long time to reflect changes

### ISSUE THREAD

**Issue by aushilfsalien** [dovrosenberg/foundry-simple-weather#47]
Some weather effects are only visible after closing browser tab and reloading foundry

Solution:

Did not wait long enough (took over 3 minutes to change the weather fx) and didn't read the manual beforehand. Sorry! :(

**Comment by dovrosenberg** [comment]
ugh - 3 minutes?  I'll keep digging in with fx master to see if there's some workaround.

@aushilfsalien - if the workaround was to create a new version of the FXMaster package (the author isn't responding to my offer to fix the issue), would you use it?

---------------------
Steps to reproduce the behavior:

login as gamemaster to foundry on forge
enable simple weather, simple calendar and fx master modules, deactivate other modules
choose fx master as special effects provider for simple weather
change weather to via module menu to "dark storm clouds"
weather doesn't change until browser tab is closed, a simple reload doesn't work

**Comment by aushilfsalien** [comment]
Hard to say. I haven't been using foundryvtt for long and can't yet estimate how much work the updates will cause me.

On the other hand: Are you sure you want to take over the maintenance of two modules? If I'm guessing correctly, that would be the consequence, right?

________________________________

**Comment by dovrosenberg** [comment]
Still don't have a solution here, but as of version 1.12.1 at least, it appears limited to clouds taking a long time to start/stop

**Comment by dovrosenberg** [comment]
Are you still having this issue?  If so, see if v1.14.0 helps.

Clouds turning off is still slow (~10 seconds) but I think other scenarios should be reasonably quick.

**Comment by dovrosenberg** [comment]
I think I found a workaround here.  I believe v1.15.0 fixes this issue (and some related ones).  Let me know if it works for you @aushilfsalien

**Comment by Von-Junzt** [comment]
Hey, I’m sorry, I couldn’t find the time to answer, but now I did 😉 It’s amazing! Weather generation time is really quick. Thank you very much for this!


Von: Dov Rosenberg ***@***.***>
Gesendet: Montag, 26. August 2024 13:39
An: dovrosenberg/foundry-simple-weather ***@***.***>
Cc: aushilfsalien ***@***.***>; Mention ***@***.***>
Betreff: Re: [dovrosenberg/foundry-simple-weather] [BUG/FEATURE REQUEST] FXMaster can take a really long time to reflect changes (Issue #47)


Are you still having this issue? If so, see if v1.14.0 helps.

Clouds turning off is still slow (~10 seconds) but I think other scenarios should be reasonably quick.
