### ISSUE TITLE
Option of having only the Weather dialog

### ISSUE THREAD

**Issue by SesuUisu** [dovrosenberg/foundry-simple-weather#5]
Having the date and time a second time open on the screen while working with Simple Calendar is just taking space on the screen.

**Comment by Peach774** [comment]
Seconding this - why does this not pop out of the simple time popout thingy?

**Comment by dovrosenberg** [comment]
First of all, thank you both for taking the time to try it out - I honestly wasn't expecting anyone to use it. :) 

Version 1.1.0 will show just the weather side, if you don't have Simple Calendar.  It will be easy to make that an option to turn off the time/date when you do have Simple Calendar, too.  

@Peach774 - how would you see this popping out, specifically?

**Comment by SesuUisu** [comment]
> Seconding this - why does this not pop out of the simple time popout thingy?
That is something Small Weather is doing (the other module). I'm quite happy that Simple Weather doesn't need SmallTime module as I do not need two time keeping modules.

**Comment by elsarfhem** [comment]
Yes, please show only weather information. Date/time is already visible with SimpleCalendar.

**Comment by dovrosenberg** [comment]
Added in v1.2.0
