### ISSUE TITLE
[FEATURE REQUEST] Send current weather to chat again

### ISSUE THREAD

**Issue by bloy** [dovrosenberg/foundry-simple-weather#53]
When resetting for a new session, I like to clear out the chat and archive it, and do other housekeeping to keep the world from getting too bloated. I'd like a way to remind players at the start of a new session what the current day's weather is.

**Describe the solution you'd like**

A button to re-send the chat card to chat without changing the weather would work. An API call available to macros would be even better.

**Describe alternatives you've considered**

Current alternatives include just changing the current weather at the start of the new session or whenever we need to be reminded of the weather.

**Comment by dovrosenberg** [comment]
Makes sense.  Just need to figure out the best UI of this (would prefer to avoid cluttering up with rarely used button), but this should be easy to knock off.

**Comment by dovrosenberg** [comment]
Released in v1.10.0
