### ISSUE TITLE
[REQUEST]Calendar log

### ISSUE THREAD

**Issue by Issacar13** [dovrosenberg/foundry-simple-weather#54]
It would be nice if weather could be logged in simple calendar (create a note daily for weather).

**Comment by Issacar13** [comment]
Also, if the gm scrolls back the calendar, instead of generating a new weather for a day which has a log, the module would use that weather instead.

**Comment by dovrosenberg** [comment]
Released in version 1.11.0.  See readme for details.

**Comment by Issacar13** [comment]
That's exactly what I had in mind! I haven't played with the calendar too much yet to see if there is any issues. Thank you so much!
