### ISSUE TITLE
[BUG] Localization not working

### ISSUE THREAD

**Issue by SesuUisu** [dovrosenberg/foundry-simple-weather#58]
SW is only in English (Window, settings, and chat output). While the rest of the UI is in German. 
Tested with no other modules and a new world. 

SW 1.11.0 (I think it was already with the previous version, but don't know when it happened).
FoundryVTT 11.315

**Comment by dovrosenberg** [comment]
Hmmm... I can't reproduce this (at least not after updating the language file you just sent).  Can you try new v1.11.1 and see if it persists?

**Comment by SesuUisu** [comment]
Somehow that solved. I will keep an eye on it, if it will happen again.

**Comment by dovrosenberg** [comment]
I wonder if the old file had some invalid JSON - I didn't see any, but that might explain it.
