### ISSUE TITLE
[FEATURE] Per Scene Turn On/Off Weather

### ISSUE THREAD

**Issue by apoapostolov** [dovrosenberg/foundry-simple-weather#63]
Right now Simple Weather applies FX for weather to all scenes, screwing landing pages, Lock Pan/Zoom image scenes, and more. A per Scene support to turn on and off weather the same SimpleTime can turn on and off time and darkness control on each scene would greatly improve this mod.

**Comment by dovrosenberg** [comment]
I'm not necessarily opposed to it, but you can manually disable the FX using the weather FX on/off button (looks like a raining cloud on the right side of the toolbar).  Isn't that almost as easy as managing across scenes?

![image](https://github.com/dovrosenberg/foundry-simple-weather/assets/4704591/777391b3-0343-4987-ae2d-0408aa1c1b64)

**Comment by apoapostolov** [comment]
Thank you for considering this. I do not use the UI constantly for some reasons (limited screen space, the UI is not as polished as SimpleTime so it isn't very nice to look compared to other mods I use, sorry if this is a bit harsh but it is a reason) and this is why I do not always have access to this button. I am also a DM who prepares his scenes prior game so being able to exclude my template for locked image scenes, and exclude my interior dungeons and my landing page, would be critical for me to use this mod.

**Comment by dovrosenberg** [comment]
Got it - makes sense.  This will take some time, but I'll definitely work on it.

**Comment by dovrosenberg** [comment]
I agree that it makes sense to have an attachment to Small Time if I can figure out how.  I'll take a look at it and add a separate issue.  I'm (obviously) not a great designer, so not sure about the visual overhaul...

**Comment by dovrosenberg** [comment]
Added ability to turn FX on/off by scene in 1.14.0

**Comment by apoapostolov** [comment]
Thank you!
