### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Daegybyte** [dovrosenberg/foundry-simple-weather#67]
**Describe the bug**
JSON needs fixing for version: 1.13.0 -> 1.13.1

**Screenshots**
<img width="974" alt="Screenshot 2024-05-28 at 10 29 10 AM" src="https://github.com/dovrosenberg/foundry-simple-weather/assets/55812910/71898c72-7c5c-4823-b1c6-4a4db6e9635d">

**Comment by Daegybyte** [comment]
Result is a loop of update prompt and old version remaining.

<img width="281" alt="Screenshot 2024-05-28 at 10 46 41 AM" src="https://github.com/dovrosenberg/foundry-simple-weather/assets/55812910/217a8c8d-b499-45a3-9f7d-4d2a8b79a1ad">
<img width="476" alt="Screenshot 2024-05-28 at 10 46 52 AM" src="https://github.com/dovrosenberg/foundry-simple-weather/assets/55812910/fba67907-0705-4ac7-bd3d-f4556b9826d2">

**Comment by dovrosenberg** [comment]
Sorry!  I made the mistake of releasing this right before moving, so I've been unable to get back to it.  I think it should be fixed now.

**Comment by Daegybyte** [comment]
All good. I thought about making a request to try and fix it myself. But I was hesitant to jump in haha
