### ISSUE TITLE
[BUG] Don't show the error notification for all players

### ISSUE THREAD

**Issue by Mathiam17** [dovrosenberg/foundry-simple-weather#68]
**Describe the bug**
Whenever a non-GM joins the game the error notification of incompatible versions with Simple Calendar shows up.

**To Reproduce**
1. Login as non-GM or non-assistant-GM into any foundry game with simple calendar ahead of simple weather

**Expected behavior**
Only the GM or assistant GM should see system/module errors and or version incompatible warnings.

**System info (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera
 - Foundry version: 11.315
 - Logging in as GM or player?: Player

**Comment by dovrosenberg** [comment]
Fixed in 1.13.3.  Thanks for pointing this out.
