### ISSUE TITLE
[BUG]Won't update to 1.13.1

### ISSUE THREAD

**Issue by R0gu3P403n1x** [dovrosenberg/foundry-simple-weather#69]
Using either Foundry or Forge to update modules Simple Weather keeps saying it needs to update to 1.13.1, but still installs 1.13.0.  At least according to the reported version number.

**Comment by dovrosenberg** [comment]
Sorry!  I made the mistake of releasing this right before moving, so I've been unable to get back to it.  I think it should be fixed now.
