### ISSUE TITLE
Sync with Simple Calendar - not manually adjustable

### ISSUE THREAD

**Issue by Safier516** [dovrosenberg/foundry-simple-weather#75]
When I connect Simple Weather to Simple Calendar, I can no longer write a number in the temperature box to manually set the weather. If Simple Weather is not connected to Simple Calendar, it works.

**Comment by dovrosenberg** [comment]
What version of Foundry and Simple Calendar?

**Comment by Safier516** [comment]
Version 12 - 330
Simple Weather 1.13.5
Simple Calendar 2.4.18

**Comment by dovrosenberg** [comment]
Hmmm. I can't reproduce this.  I do see that the temperature box changes color (and all the UI gets a little screwy) when it's attached, but I can successfully enter a number and generate new weather.  

Is it disabling the box for you?  Is it preventing you from typing in the box or from generating new weather?

**Comment by Safier516** [comment]
![Screenshot 2024-08-30 202149](https://github.com/user-attachments/assets/01618deb-6723-4229-91b7-f8ecf794a5b8)

**Comment by dovrosenberg** [comment]
What happens if you try to put a temperature in the box? Will it let you click in? Let you type?

**Comment by Safier516** [comment]
I can click on the box, but I can't type in any numbers.

**Comment by dovrosenberg** [comment]
Could you try disabling all modules except simple calendar and simple weather?  I wonder if it's a conflict with something else.

**Comment by Safier516** [comment]
All modules switched off and no, it doesn't work. If I replace “clear sky” with one of the other options and then try to put a number in the box, it goes back to “clear sky”.

**Comment by dovrosenberg** [comment]
Can you upgrade to 1.15.1 and see if that helps?  If it doesn't...

Hit F12 to open the debugger and at the ">" prompt in the console window type:
`game.modules.get('simple-weather').api.debugOutput()`

Hit enter and copy/paste the output (which will be long) here.

**Comment by Safier516** [comment]
simple-weather DEBUG OUTPUT
_______________________________________
isGM: true
displayOptions: {
  "dateBox": false,
  "weatherBox": true,
  "seasonBar": true,
  "biomeBar": true,
  "manualBar": true
}
dialogDisplay: true
calendarPresent: true
manualPause: false
currentClimate: 0
currentHumidity: 0
currentBiome: 
currentSeason: 0
currentSeasonSync: true
ModuleSettings.dialogDisplay: true
ModuleSettings.outputWeatherToChat: true
ModuleSettings.publicChat: true
ModuleSettings.useFX: core
ModuleSettings.FXByScene: false
ModuleSettings.attachToCalendar: true
ModuleSettings.storeInSCNotes: true
ModuleSettings.fxActive: true
getData: {
  "isGM": true,
  "displayDate": "September 07, 2024",
  "formattedDate": "6/8/2024",
  "formattedTime": "00:02:07",
  "weekday": "Saturday",
  "currentTemperature": "15°C",
  "currentDescription": "Blue white sky",
  "currentSeasonClass": "fa-sun summer",
  "biomeSelections": [
    {
      "value": "",
      "text": "Use climate/humidity"
    },
    {
      "value": "tundra",
      "text": "Tundra"
    },
    {
      "value": "alpine",
      "text": "Alpine"
    },
    {
      "value": "taiga",
      "text": "Taiga"
    },
    {
      "value": "chapparel",
      "text": "Chapparel"
    },
    {
      "value": "grassland",
      "text": "Grassland"
    },
    {
      "value": "forest",
      "text": "Forest"
    },
    {
      "value": "desert",
      "text": "Desert"
    },
    {
      "value": "savannah",
      "text": "Savannah"
    },
    {
      "value": "rainforest",
      "text": "Rainforest"
    }
  ],
  "seasonSelections": [
    {
      "value": "sync",
      "text": "Sync with Simple Calendar"
    },
    {
      "value": "0",
      "text": "Spring"
    },
    {
      "value": "1",
      "text": "Summer"
    },
    {
      "value": "2",
      "text": "Fall"
    },
    {
      "value": "3",
      "text": "Winter"
    }
  ],
  "humiditySelections": [
    {
      "value": "0",
      "text": "Barren"
    },
    {
      "value": "1",
      "text": "Modest"
    },
    {
      "value": "2",
      "text": "Verdant"
    }
  ],
  "climateSelections": [
    {
      "value": "0",
      "text": "Cold"
    },
    {
      "value": "1",
      "text": "Temperate"
    },
    {
      "value": "2",
      "text": "Hot"
    }
  ],
  "manualSelections": [
    {
      "value": "0",
      "text": "Clear sky"
    },
    {
      "value": "1",
      "text": "Fleecy clouds"
    },
    {
      "value": "2",
      "text": "Grey, windy"
    },
    {
      "value": "3",
      "text": "Dark storm cloud"
    },
    null,
    {
      "value": "5",
      "text": "Light rain"
    },
    {
      "value": "6",
      "text": "Steady rain"
    },
    {
      "value": "7",
      "text": "Heavy rain"
    },
    {
      "value": "8",
      "text": "Light fog"
    },
    {
      "value": "9",
      "text": "Fog banks"
    },
    {
      "value": "10",
      "text": "Heavy fog"
    },
    {
      "value": "11",
      "text": "Light snowfall"
    },
    {
      "value": "12",
      "text": "Moderate snowfall, windy"
    },
    {
      "value": "13",
      "text": "Heavy snow"
    },
    {
      "value": "14",
      "text": "Hail storm"
    }
  ],
  "displayOptions": {
    "dateBox": false,
    "weatherBox": true,
    "seasonBar": true,
    "biomeBar": true,
    "manualBar": true
  },
  "hideCalendar": true,
  "hideCalendarToggle": true,
  "hideWeather": false,
  "hideFXToggle": false,
  "manualPause": false,
  "fxActive": true,
  "useCelsius": true,
  "attachedMode": true,
  "showAttached": true,
  "SCContainerClasses": "fsc-of sc-right fsc-c",
  "windowPosition": {
    "bottom": 0,
    "left": 0
  },
  "containerPosition": "relative",
  "hideDialog": false
}
_______________________________________

**Comment by dovrosenberg** [comment]
Ah ha! Found it!  It's because the calendar is in compact mode.  I'll work on fixing it now.
