### ISSUE TITLE
Weather Window Covers canvas even when not open

### ISSUE THREAD

**Issue by EmoCthulhu** [dovrosenberg/foundry-simple-weather#8]
I'm finding that when simple weather is active, the area that the weather expansion tab takes up is unusable on the Foundry canvas, even when it's not open. For instance if I have the calendar next to a token, I cannot select the token, or when the calendar is next to the Foundry right tools, I cannot select any buttons, scenes or actors in the space where the weather expansion would be.

**Comment by EmoCthulhu** [comment]
Guess I should mention my configuration. Foundry V11 Build 313. All my systems are affected, Simple World Building, Dragonbane, ALIEN, Blade Runner, Starfinder, Vaesen, Coriolis, Cyberpunk RED, CY_BORG, Cities Without Number. I run most of my games hosted on the Forge, but it also happens on my local Foundry installation.

**Comment by dovrosenberg** [comment]
Well, that's not very useful, is it?  I think I see the issue and will work on a fix.

**Comment by EmoCthulhu** [comment]
Excellent. Love the module, wish I could enable it!

**Comment by dovrosenberg** [comment]
Fixed in v1.3.1
