### ISSUE TITLE
[REQUEST] Toggle OFF or ON which maps are affected by the Simple Weather

### ISSUE THREAD

**Issue by iwontgiveyoumyname** [dovrosenberg/foundry-simple-weather#80]
It would be great to be able to determine for each scene if the weather of the Simple Weather can affect that scene in particular (almost like the Small Time where we can let the light be determined automatically or manually, so something like "Control of weather: YES or NO").

With that, we could be able to keep the weather without having to reneable it when switching the scene AND also be able to determine which scene are exterior or interior.

**Comment by dovrosenberg** [comment]
v1.15.0 allows this behavior.  There's a configuration setting to let you specify that FX are enabled/disabled by scene rather than globally.
