### ISSUE TITLE
[BUG] Can't set or change Scene Ambient weather

### ISSUE THREAD

**Issue by LordValerius** [dovrosenberg/foundry-simple-weather#81]
**Describe the bug**
With Simple Weather enabled, you can't set or change current weather in Scene Ambience

**To Reproduce**
1. Right Click on a Scene Navigation tab and select "Configure"
2. Click on Ambience tab, then click on Weather drop down.
3. Scroll down to any available weather selection, ie. Rain.
4. Nothing happens, error drops in Console (ss attached)

**Expected behavior**
It should load the default Foundry Rain effect, and does so once Simple Weather is disabled.

**Screenshots**
![image](https://github.com/user-attachments/assets/c84019ab-3e6d-40d4-82be-768217c16afd)

**System info (please complete the following information):**
 - OS: Win 10
 - Browser: Edge
 - Foundry version: 12.331 - Simple Weather version 1.15.0
 - Logging in as GM

**Comment by dovrosenberg** [comment]
I can't reproduce the console error - I suspect it's an interaction with another module.  That said, in a clean setup you can pick something from the dropdown, but it doesn't actually change the weather.  v1.15.1 fixes this (with a caveat as noted in the readme under known issues).

Let me know what happens in your setup with v1.15.1, though.  If this doesn't fix it, we can dig in to see what other module is causing the issue (in combination with Simple Weather).
