### ISSUE TITLE
Manifest warning

### ISSUE THREAD

**Issue by grz0** [dovrosenberg/foundry-simple-weather#83]
**Describe the bug**
Foundry logs a warning because of a problem in manifest of this module

**To Reproduce**
1. Check warnings in Setup page

**Expected behavior**
No warnings.

**Screenshots**
![image](https://github.com/user-attachments/assets/c66906e8-ee0f-495d-b553-232f499e630c)

**System info (please complete the following information):**
Foundry v12.331

**Additional context**
Line in manifest file which causes the warning:

`"## version": "will be added when we build",`

**Comment by dovrosenberg** [comment]
This will be fixed in the next release.
